<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>treetop</string>
	</array>
	<key>name</key>
	<string>TreeTop</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Load in additional libraries</string>
			<key>match</key>
			<string>\b(require|gem)\b</string>
			<key>name</key>
			<string>keyword.source.treetop</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[A-Z]\w*(?=((\.|::)[A-Za-z]|\[))</string>
			<key>name</key>
			<string>support.class.treetop</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.treetop</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.treetop</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.treetop</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>string.treetop</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.treetop</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>single quoted string (does not allow interpolation)</string>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.treetop</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.treetop</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>string.treetop</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.class.treetop</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.treetop</string>
				</dict>
			</dict>
			<key>match</key>
			<string>grammar (\w+)</string>
			<key>name</key>
			<string>meta.function.method.with-arguments.treetop</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.def.treetop</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.treetop</string>
				</dict>
			</dict>
			<key>match</key>
			<string>rule (\w+)</string>
			<key>name</key>
			<string>meta.function.method.with-arguments.treetop</string>
		</dict>
		<dict>
			<key>match</key>
			<string>=</string>
			<key>name</key>
			<string>keyword.operator.assignment.treetop</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+=</string>
			<key>name</key>
			<string>keyword.operator.comparison.treetop</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(%|&amp;amp;|\*\*|\*|\+|\-|/)</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.treetop</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>TreeTop control keyword</string>
			<key>match</key>
			<string>\b(BEGIN|begin|case|class|else|elsif|END|end|ensure|for|grammar|if|in|include|module|rescue|rule|then|unless|until|when|while)\b</string>
			<key>name</key>
			<string>keyword.control.treetop</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>TreeTop comment</string>
			<key>match</key>
			<string>^ *#.*$</string>
			<key>name</key>
			<string>comment.treetop</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^ +\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.treetop</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>single quoted string (does not allow interpolation)</string>
			<key>end</key>
			<string>\]\+\? +$</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.treetop</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.treetop</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>string.treetop</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.treetop</string>
	<key>uuid</key>
	<string>0772a8a8-108d-4543-94d0-abe7b3912aa2</string>
</dict>
</plist>